apiVersion: batch/v1
kind: Job
metadata:
  name: nodriver-bench-job
  namespace: multion
spec:
  completions: 1000
  parallelism: 20
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: nodriver-bench
          image: harbor.kymyth.com/library/nodriver-bench:latest
      restartPolicy: OnFailure
  backoffLimit: 4
